import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import NavBar from "../components/shared/NavBar/NavBar";
import { ThemeProvider } from "../components/shared/ThemeProvider";
import "./globals.css";

const lexend = Lexend({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-lexend",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${lexend.className} text-foreground antialiased`}>
        <ThemeProvider attribute='class' defaultTheme='dark'>
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
